package com.anirudh.bingo.exception;

public enum ErrorType {
    ROOM_CLOSED,
    ROOM_FULL,
    PLAYER_ALREADY_IN_ROOM,
    PLAYER_NOT_IN_ROOM,
    NOT_ROOM_HOST,
    INSUFFICIENT_PLAYERS,
    ROOM_NOT_FOUND,
    ROOM_NOT_IN_PROGRESS,
    NOT_PLAYERS_TURN,
    GAME_ALREADY_STARTED,
    GAME_NOT_STARTED,
    GAME_ALREADY_FINISHED,
    INVALID_NUMBER,
    NUMBER_ALREADY_CALLED,
    INTERNAL_SERVER_ERROR
}
